parameters:
  bind_host: 0.0.0.0
  bind_port: 11221

  avr_host: 127.0.0.1
  avr_port: 11222
  avr_timeout: 180

  queue_interval: 1

  local_ws_endpoint: '192.168.1.101:11221'
  external_ws_endpoint: 'api.lights.host/websocket'

  stream: '1I_XcCC9CiE?autoplay=1'

  relays:
    - {id: 0, name: 'Czerwony'}
    - {id: 1, name: 'Zielony'}
    - {id: 2, name: 'Niebieski'}
    - {id: 3, name: 'Gwiazda'}