services:
  # Websocket driver
  loop:
    factory: ['\React\EventLoop\Factory', 'create']
    class: '\React\EventLoop\LoopInterface'

  socket_factory:
    class: 'Syntax\WebSocket\ServerSocket\SocketFactory'
    arguments: ['%bind_host%', '%bind_port%']

  socket:
    factory: ['@socket_factory', 'createSocket']
    arguments: ['@loop']
    class: '\React\Socket\Server'

  server:
    class: '\Syntax\WebSocket\ServerSocket\ServerWrapper'
    arguments: ['@loop', '@socket', '@message_component']

  message_component:
    class: '\Syntax\WebSocket\MessageComponent'
    arguments: ['@clients_inmemory', '@statistics', '@database', '@controllers_dispatcher', '@start_message_states', '@avr', '@colors_inmemory']

  controllers_dispatcher:
    class: '\Syntax\WebSocket\ControllersDispatcher'

  # AVR module
  avr:
    class: '\Syntax\Service\WebSocket\AVRService'
    arguments: ['%avr_host%', '%avr_port%', '%avr_timeout%', '@database']

  # IN-Memory
  clients_inmemory:
    class: '\Syntax\WebSocket\InMemory\Clients'

  lights_inmemory:
    class: '\Syntax\WebSocket\InMemory\Lights'
    arguments: ['@avr']

  colors_inmemory:
    class: '\Syntax\WebSocket\InMemory\ColorChangesQueue'
    arguments: ['@loop', '@avr', '@database', '@clients_inmemory', '%colors_changes_queue_default_duration%']

  # Common
  database:
    class: '\Syntax\Service\Database'
    arguments: ['%sqlite%']

  statistics:
    class: '\Syntax\Service\Stats'
    arguments: ['@database', '@clients_inmemory']

  # Controllers
  ChangeState:
    class: '\Syntax\Controller\ChangeStateController'
    arguments: ['@lights_inmemory', '@clients_inmemory', '@loop', '@database']

  ChangeColor:
      class: '\Syntax\Controller\ChangeColorController'
      arguments: ['@colors_inmemory', '@database']

  start_message_states:
    class: '\Syntax\Service\WebSocket\ChangeStateStartMessage'
    arguments: ['@lights_inmemory']