services:
  # Websocket driver
  loop:
    factory: ['\React\EventLoop\Factory', 'create']
    class: '\React\EventLoop\LoopInterface'

  socket_factory:
    class: 'Syntax\WebSocket\ServerSocket\SocketFactory'
    arguments: ['%bind_host%', '%bind_port%']

  socket:
    factory: ['@socket_factory', 'createSocket']
    arguments: ['@loop']
    class: '\React\Socket\Server'

  server:
    class: '\Syntax\WebSocket\ServerSocket\ServerWrapper'
    arguments: ['@loop', '@socket', '@message_component']

  message_component:
    class: '\Syntax\WebSocket\MessageComponent'
    arguments: ['@clients_inmemory', '@statistics', '@database', '@controllers_dispatcher']

  controllers_dispatcher:
    class: '\Syntax\WebSocket\ControllersDispatcher'

  # IN-Memory
  clients_inmemory:
    class: '\Syntax\WebSocket\InMemory\Clients'

  lights_inmemory:
    class: '\Syntax\WebSocket\InMemory\Lights'
    arguments: ['%avr_host%', '%avr_port%', '%avr_timeout%']

  # Common
  database:
    class: '\Syntax\Service\Database'
    arguments: ['%sqlite%']

  statistics:
    class: '\Syntax\Service\Stats'
    arguments: ['@database', '@clients_inmemory']

  # Controllers
  ChangeState:
    class: '\Syntax\Controller\ChangeStateController'
    arguments: ['@lights_inmemory', '@clients_inmemory', '@loop', '@database']